/*
 * File: app/view/crtWorldPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mty.view.crtWorldPanel', {
    extend: 'Ext.form.Panel',

    draggable: true,
    height: 250,
    id: 'id_extNewWorld_panel',
    width: 400,
    bodyPadding: 10,
    title: '新建场景',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            tools: [
                {
                    xtype: 'tool',
                    id: 'btCloseWin_crtWorld',
                    tooltip: '关闭',
                    type: 'close'
                }
            ]
        });

        me.callParent(arguments);
    }

});