/*
 * File: app/view/Render_Cam_Conf.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mty.view.Render_Cam_Conf', {
    extend: 'Ext.panel.Panel',

    height: 605,
    id: 'id_renderConf',
    width: 350,
    autoScroll: true,
    layout: {
        type: 'column'
    },
    title: '渲染配置',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            tools: [
                {
                    xtype: 'tool',
                    tooltip: '关闭插件',
                    type: 'close'
                }
            ],
            items: [
                {
                    xtype: 'panel',
                    baseCls: 'baseCls:\'.my-panel-no-border{border-style:none}\'',
                    height: 132,
                    width: 326,
                    title: '',
                    items: [
                        {
                            xtype: 'fieldset',
                            height: 120,
                            width: 313,
                            title: '场景列表'
                        }
                    ]
                },
                {
                    shrinkWrap: 1
                },
                {
                    xtype: 'panel',
                    baseCls: 'baseCls:\'.my-panel-no-border{border-style:none}\'',
                    height: 155,
                    layout: {
                        type: 'column'
                    },
                    title: '',
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var curCam = global_oakEngineManager.getMainEngineObject().m_camActivityCam;
                                global_extPanelManager.m_oRenderConfPlugin.addCam(curCam);
                            },
                            id: 'id_renderConf_addCamBtn',
                            width: 36,
                            text: '+'
                        },
                        {
                            xtype: 'textfield',
                            width: 144,
                            inputId: 'id_renderConf_camName',
                            fieldLabel: '相机名',
                            labelWidth: 50
                        },
                        {
                            xtype: 'fieldset',
                            height: 121,
                            id: 'id_camItemSet',
                            width: 312,
                            autoScroll: true,
                            layout: {
                                type: 'column'
                            },
                            title: '相机列表'
                        }
                    ]
                },
                {

                },
                {

                },
                {
                    xtype: 'panel',
                    baseCls: 'baseCls:\'.my-panel-no-border{border-style:none}\'',
                    height: 188,
                    width: 326,
                    layout: {
                        type: 'column'
                    },
                    title: '',
                    items: [
                        {
                            xtype: 'panel',
                            baseCls: '\'.my-panel-no-border{border-style:none}\'',
                            height: 23,
                            width: 303,
                            title: '',
                            items: [
                                {
                                    xtype: 'label',
                                    height: 14,
                                    width: 317,
                                    text: '-相机配置-'
                                }
                            ]
                        },
                        {
                            xtype: 'textfield',
                            width: 84,
                            fieldLabel: '视角',
                            labelWidth: 30
                        },
                        {
                            xtype: 'label',
                            height: 21,
                            width: 237,
                            text: '背景色：'
                        },
                        {
                            xtype: 'panel',
                            baseCls: 'baseCls:\'.my-panel-no-border{border-style:none}\'',
                            height: 167,
                            width: 312,
                            title: '',
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: 'id_text_camColor_r',
                                    fieldLabel: 'R',
                                    labelWidth: 30
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'id_text_camColor_g',
                                    fieldLabel: 'G',
                                    labelWidth: 30
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'id_text_camColor_b',
                                    fieldLabel: 'B',
                                    labelWidth: 30
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'id_text_camColor_a',
                                    fieldLabel: 'A',
                                    labelWidth: 30
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var tmpObjr = Ext.getCmp('id_text_camColor_r');
                                        var tmpObjg = Ext.getCmp('id_text_camColor_g');
                                        var tmpObjb = Ext.getCmp('id_text_camColor_b');
                                        var tmpObja = Ext.getCmp('id_text_camColor_a');
                                        var clorVec4 = new okVec4(Number(tmpObjr.getValue().toString()),
                                        Number(tmpObjg.getValue().toString()),
                                        Number(tmpObjb.getValue().toString()),
                                        Number(tmpObja.getValue().toString()));
                                        global_oakEngineManager.m_oRenderConfPlugin._setBackColor_(clorVec4);
                                    },
                                    text: '设置'
                                },
                                {
                                    xtype: 'slider',
                                    width: 312,
                                    value: 40,
                                    fieldLabel: 'Label'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});