/*
 * File: app/view/ControlMainWindow.js
 * Date: Sat Nov 24 2012 00:01:06 GMT+0800 (ÖÐ¹ú±ê×¼Ê±¼ä)
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mty.view.ControlMainWindow', {
    extend: 'Ext.panel.Panel',

    frame: true,
    height: 652,
    id: 'ExtControlMainWindow',
    width: 1200,
    layout: {
        type: 'absolute'
    },
    hideCollapseTool: false,
    title: 'WebEngine',
    titleCollapse: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    frame: true,
                    height: 25,
                    items: [
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: '环境编辑器',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        handler: function(item, event) {
                                            if (null == global_extPanelManager.v_extEnvirEditor) {
                                                global_extPanelManager.m_oEnvirEditorObj = new EnvirEditorObj();
                                                global_extPanelManager.m_oEnvirEditorObj.init();
                                            } else {
                                                global_extPanelManager.m_oEnvirEditorObj.setMenuShow();
                                            }
                                        },
                                        text: '地形工具'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: '光照工具'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                global_extPanelManager.m_oEntiMgrPlugin.setMenuShow();
                            },
                            text: '模型管理器'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: '粒子编辑器'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    frame: true,
                    height: 25,
                    id: '',
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, event) {

                                //Ext.MessageBox.alert('提示',"I'm ready to show u a new world! :-)");
                                event_createNewWorld();
                            },
                            icon: 'media/ico/window.png',
                            text: '新建'
                        },
                        {
                            xtype: 'button',
                            text: '打开'
                        },
                        {
                            xtype: 'button',
                            text: '保存'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var usrOpr = global_oakEngineManager.getMainEngineObject().m_usrOpera;
                                usrOpr.m_oCurOperaMod.clearAll();
                                usrOpr.m_oCurOperaMod = usrOpr.m_oMoveCamObj;
                            },
                            text: 'Move'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var usrOpr = global_oakEngineManager.getMainEngineObject().m_usrOpera;
                                usrOpr.m_oCurOperaMod.clearAll();
                                usrOpr.m_oCurOperaMod = usrOpr.m_oSglEntiOperaObj;
                            },
                            text: 'Select'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'textareafield',
                            width: 150,
                            inputId: 'id_eye_world',
                            name: 'eye_world',
                            fieldLabel: 'eye',
                            labelWidth: 20,
                            emptyText: '-',
                            growAppend: ' -'
                        },
                        {
                            xtype: 'textareafield',
                            width: 150,
                            inputId: 'id_to_world',
                            name: 'to_world',
                            fieldLabel: 'to',
                            labelWidth: 20,
                            emptyText: '-'
                        },
                        {
                            xtype: 'textareafield',
                            width: 150,
                            inputId: 'id_up_world',
                            name: 'up_world',
                            fieldLabel: 'up',
                            labelWidth: 20,
                            emptyText: '-'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: 'Scene&Cam'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});