/*
 * File: app/view/sletMenu.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mty.view.sletMenu', {
    extend: 'Ext.panel.Panel',

    draggable: true,
    height: 25,
    width: 174,
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    height: 25,
                    width: 159,
                    items: [
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                global_oakEngineManager.getMainEngineObject().m_usrOpera.m_oSglEntiOperaObj.m_iOprCodec = 0x00000000;
                            },
                            text: '移动'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                global_oakEngineManager.getMainEngineObject().m_usrOpera.m_oSglEntiOperaObj.m_iOprCodec = 0x00000001;
                            },
                            text: '缩放'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                global_oakEngineManager.getMainEngineObject().m_usrOpera.m_oSglEntiOperaObj.m_iOprCodec = 0x00000002;
                            },
                            text: '旋转'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                global_oakEngineManager.getMainEngineObject().m_usrOpera.m_oSglEntiOperaObj.sletBoundingBoxDesty();
                                global_extPanelManager.getMainWindowObj().sletEntiOperaMenuHide();
                                global_oakEngineManager.getMainEngineObject().m_usrOpera.m_oSglEntiOperaObj.clearAll();
                            },
                            text: '取消'
                        },
                        {
                            xtype: 'tbseparator'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});