/*
 * File: app/view/EntiMgrPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Mty.view.EntiMgrPanel', {
    extend: 'Ext.tree.Panel',

    draggable: true,
    height: 501,
    html: ' <input type="file" id="id_model_file_input" style="width: 0px; display: inline;">',
    id: 'id_entiMgr',
    width: 300,
    title: '实体管理器',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {

            },
            columns: [
                {
                    xtype: 'treecolumn',
                    dataIndex: 'text',
                    flex: 1,
                    text: 'Nodes'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    width: 230,
                    items: [
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                document.getElementById('id_model_file_input').click();
                            },
                            allowDepress: false,
                            enableToggle: false,
                            pressed: false,
                            text: '+'
                        },
                        {
                            xtype: 'textareafield',
                            width: 120,
                            inputId: 'id_entiName',
                            fieldLabel: 'Name',
                            labelWidth: 50
                        },
                        {
                            xtype: 'textareafield',
                            width: 120,
                            inputId: 'id_preEntiName',
                            fieldLabel: '父对象',
                            labelWidth: 50
                        },
                        {
                            xtype: 'tbspacer'
                        },
                        {
                            xtype: 'tbseparator'
                        }
                    ]
                }
            ],
            tools: [
                {
                    xtype: 'tool',
                    tooltip: 'close',
                    type: 'close'
                }
            ]
        });

        me.callParent(arguments);
    }

});